/*
 * This file was generated automatically by xsubpp version 1.9507 from the 
 * contents of LinkParser.xs. Do not edit this file, edit LinkParser.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "LinkParser.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "link-includes.h"

static int
not_here(char *s)
{
    croak("%s not implemented on this architecture", s);
    return -1;
}

static double
constant(char *name, int len, int arg)
{
    errno = EINVAL;
    return 0;
}

#line 31 "LinkParser.c"
XS(XS_Lingua__LinkParser_constant)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::constant(sv,arg)");
    {
#line 27 "LinkParser.xs"
	STRLEN		len;
#line 40 "LinkParser.c"
	SV *	sv = ST(0);
	char *	s = SvPV(sv, len);
	int	arg = (int)SvIV(ST(1));
	double	RETVAL;
#line 33 "LinkParser.xs"
	RETVAL = constant(s,len,arg);
#line 47 "LinkParser.c"
	ST(0) = sv_newmortal();
	sv_setnv(ST(0), (double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_dictionary_create)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::dictionary_create(name, post_process_file_name)");
    {
	char *	name = (char *)SvPV(ST(0),PL_na);
	char *	post_process_file_name = (char *)SvPV(ST(1),PL_na);
	Dictionary	RETVAL;

	RETVAL = dictionary_create(name, post_process_file_name);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Dictionary", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_dictionary_delete)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::dictionary_delete(dict)");
    {
	Dictionary	dict;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Dictionary")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dict = (Dictionary) tmp;
	}
	else
	    croak("dict is not of type Dictionary");

	RETVAL = dictionary_delete(dict);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_dictionary_get_max_cost)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::dictionary_get_max_cost(dict)");
    {
	Dictionary	dict;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Dictionary")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dict = (Dictionary) tmp;
	}
	else
	    croak("dict is not of type Dictionary");

	RETVAL = dictionary_get_max_cost(dict);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_and_cost)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_and_cost(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_and_cost(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_compute_union)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_compute_union(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_compute_union(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_create)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: Lingua::LinkParser::linkage_create(index, sent, opts)");
    {
	int	index = (int)SvIV(ST(0));
	Sentence	sent;
	Parse_Options	opts;
	Linkage	RETVAL;

	if (sv_derived_from(ST(1), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	if (sv_derived_from(ST(2), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(2)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = linkage_create(index, sent, opts);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Linkage", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_delete)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_delete(linkage)");
    {
	Linkage	linkage;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	linkage_delete(linkage);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_linkage_disjunct_cost)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_disjunct_cost(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_disjunct_cost(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_link_domain_names)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_get_link_domain_names(linkage, index)");
    {
	Linkage	linkage;
	int	index = (int)SvIV(ST(1));
	char **	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_link_domain_names(linkage, index);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "charPtrPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_link_label)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_get_link_label(linkage, index)");
    {
	Linkage	linkage;
	int	index = (int)SvIV(ST(1));
	char *	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_link_label(linkage, index);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_link_length)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_get_link_length(linkage, index)");
    {
	Linkage	linkage;
	int	index = (int)SvIV(ST(1));
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_link_length(linkage, index);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_link_llabel)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_get_link_llabel(linkage, index)");
    {
	Linkage	linkage;
	int	index = (int)SvIV(ST(1));
	char *	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_link_llabel(linkage, index);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_link_lword)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_get_link_lword(linkage, index)");
    {
	Linkage	linkage;
	int	index = (int)SvIV(ST(1));
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_link_lword(linkage, index);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_link_num_domains)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_get_link_num_domains(linkage, index)");
    {
	Linkage	linkage;
	int	index = (int)SvIV(ST(1));
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_link_num_domains(linkage, index);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_link_rlabel)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_get_link_rlabel(linkage, index)");
    {
	Linkage	linkage;
	int	index = (int)SvIV(ST(1));
	char *	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_link_rlabel(linkage, index);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_link_rword)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_get_link_rword(linkage, index)");
    {
	Linkage	linkage;
	int	index = (int)SvIV(ST(1));
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_link_rword(linkage, index);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_num_links)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_get_num_links(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_num_links(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_num_sublinkages)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_get_num_sublinkages(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_num_sublinkages(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_num_words)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_get_num_words(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_num_words(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_sentence)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_get_sentence(linkage)");
    {
	Linkage	linkage;
	Sentence	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_sentence(linkage);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Sentence", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_violation_name)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_get_violation_name(linkage)");
    {
	Linkage	linkage;
	char *	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_violation_name(linkage);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_word)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_get_word(linkage, w)");
    {
	Linkage	linkage;
	int	w = (int)SvIV(ST(1));
	char *	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_word(linkage, w);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_get_words)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_get_words(linkage)");
    {
	Linkage	linkage;
	char **	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_get_words(linkage);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "charPtrPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_has_inconsistent_domains)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_has_inconsistent_domains(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_has_inconsistent_domains(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_is_canonical)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_is_canonical(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_is_canonical(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_is_improper)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_is_improper(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_is_improper(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_link_cost)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_link_cost(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_link_cost(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_post_process)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_post_process(linkage, postprocessor)");
    {
	Linkage	linkage;
	PostProcessor	postprocessor;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	if (sv_derived_from(ST(1), "PostProcessor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    postprocessor = (PostProcessor) tmp;
	}
	else
	    croak("postprocessor is not of type PostProcessor");

	linkage_post_process(linkage, postprocessor);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_linkage_print_diagram)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_print_diagram(linkage)");
    {
	Linkage	linkage;
	char *	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_print_diagram(linkage);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_print_links_and_domains)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_print_links_and_domains(linkage)");
    {
	Linkage	linkage;
	char *	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_print_links_and_domains(linkage);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_print_postscript)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_print_postscript(linkage, mode)");
    {
	Linkage	linkage;
	int	mode = (int)SvIV(ST(1));
	char *	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_print_postscript(linkage, mode);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_set_current_sublinkage)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::linkage_set_current_sublinkage(linkage, index)");
    {
	Linkage	linkage;
	int	index = (int)SvIV(ST(1));
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_set_current_sublinkage(linkage, index);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_linkage_unused_word_cost)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::linkage_unused_word_cost(linkage)");
    {
	Linkage	linkage;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Linkage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    linkage = (Linkage) tmp;
	}
	else
	    croak("linkage is not of type Linkage");

	RETVAL = linkage_unused_word_cost(linkage);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_create)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: Lingua::LinkParser::parse_options_create()");
    {
	Parse_Options	RETVAL;

	RETVAL = parse_options_create();
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Parse_Options", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_delete)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_delete(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_delete(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_all_short_connectors)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_all_short_connectors(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_all_short_connectors(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_allow_null)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_allow_null(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_allow_null(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_batch_mode)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_batch_mode(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_batch_mode(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_disjunct_cost)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_disjunct_cost(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_disjunct_cost(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_display_bad)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_display_bad(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_display_bad(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_display_links)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_display_links(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_display_links(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_display_on)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_display_on(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_display_on(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_display_postscript)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_display_postscript(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_display_postscript(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_display_union)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_display_union(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_display_union(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_display_walls)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_display_walls(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_display_walls(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_echo_on)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_echo_on(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_echo_on(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_islands_ok)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_islands_ok(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_islands_ok(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_linkage_limit)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_linkage_limit(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_linkage_limit(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_max_memory)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_max_memory(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_max_memory(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_max_null_count)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_max_null_count(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_max_null_count(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_max_parse_time)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_max_parse_time(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_max_parse_time(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_min_null_count)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_min_null_count(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_min_null_count(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_null_block)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_null_block(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_null_block(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_panic_mode)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_panic_mode(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_panic_mode(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_screen_width)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_screen_width(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_screen_width(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_short_length)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_short_length(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_short_length(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_get_verbosity)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_get_verbosity(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_get_verbosity(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_memory_exhausted)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_memory_exhausted(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_memory_exhausted(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_reset_resources)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_reset_resources(opts)");
    {
	Parse_Options	opts;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_reset_resources(opts);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_resources_exhausted)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_resources_exhausted(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_resources_exhausted(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_parse_options_set_all_short_connectors)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_all_short_connectors(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_all_short_connectors(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_allow_null)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_allow_null(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_allow_null(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_batch_mode)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_batch_mode(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_batch_mode(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_cost_model_type)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_cost_model_type(opts, cm)");
    {
	Parse_Options	opts;
	int	cm = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_cost_model_type(opts, cm);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_disjunct_cost)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_disjunct_cost(opts, disjunct_cost)");
    {
	Parse_Options	opts;
	int	disjunct_cost = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_disjunct_cost(opts, disjunct_cost);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_display_bad)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_display_bad(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_display_bad(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_display_links)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_display_links(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_display_links(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_display_on)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_display_on(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_display_on(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_display_postscript)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_display_postscript(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_display_postscript(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_display_union)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_display_union(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_display_union(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_display_walls)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_display_walls(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_display_walls(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_echo_on)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_echo_on(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_echo_on(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_islands_ok)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_islands_ok(opts, islands_ok)");
    {
	Parse_Options	opts;
	int	islands_ok = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_islands_ok(opts, islands_ok);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_linkage_limit)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_linkage_limit(opts, linkage_limit)");
    {
	Parse_Options	opts;
	int	linkage_limit = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_linkage_limit(opts, linkage_limit);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_max_memory)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_max_memory(opts, mem)");
    {
	Parse_Options	opts;
	int	mem = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_max_memory(opts, mem);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_max_null_count)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_max_null_count(opts, null_count)");
    {
	Parse_Options	opts;
	int	null_count = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_max_null_count(opts, null_count);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_max_parse_time)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_max_parse_time(opts, secs)");
    {
	Parse_Options	opts;
	int	secs = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_max_parse_time(opts, secs);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_min_null_count)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_min_null_count(opts, null_count)");
    {
	Parse_Options	opts;
	int	null_count = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_min_null_count(opts, null_count);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_null_block)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_null_block(opts, null_block)");
    {
	Parse_Options	opts;
	int	null_block = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_null_block(opts, null_block);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_panic_mode)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_panic_mode(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_panic_mode(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_screen_width)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_screen_width(opts, val)");
    {
	Parse_Options	opts;
	int	val = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_screen_width(opts, val);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_short_length)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_short_length(opts, short_length)");
    {
	Parse_Options	opts;
	int	short_length = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_short_length(opts, short_length);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_set_verbosity)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::parse_options_set_verbosity(opts, verbosity)");
    {
	Parse_Options	opts;
	int	verbosity = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	parse_options_set_verbosity(opts, verbosity);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_parse_options_timer_expired)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::parse_options_timer_expired(opts)");
    {
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = parse_options_timer_expired(opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_post_process_close)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::post_process_close(postprocessor)");
    {
	PostProcessor	postprocessor;

	if (sv_derived_from(ST(0), "PostProcessor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    postprocessor = (PostProcessor) tmp;
	}
	else
	    croak("postprocessor is not of type PostProcessor");

	post_process_close(postprocessor);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_post_process_open)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::post_process_open(dictname, path)");
    {
	char *	dictname = (char *)SvPV(ST(0),PL_na);
	char *	path = (char *)SvPV(ST(1),PL_na);
	Postprocessor *	RETVAL;

	RETVAL = post_process_open(dictname, path);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "PostprocessorPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_sentence_create)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::sentence_create(input_string, dict)");
    {
	char *	input_string = (char *)SvPV(ST(0),PL_na);
	Dictionary	dict;
	Sentence	RETVAL;

	if (sv_derived_from(ST(1), "Dictionary")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    dict = (Dictionary) tmp;
	}
	else
	    croak("dict is not of type Dictionary");

	RETVAL = sentence_create(input_string, dict);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Sentence", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_sentence_delete)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::sentence_delete(sent)");
    {
	Sentence	sent;

	if (sv_derived_from(ST(0), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	sentence_delete(sent);
    }
    XSRETURN_EMPTY;
}

XS(XS_Lingua__LinkParser_sentence_disjunct_cost)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::sentence_disjunct_cost(sent, i)");
    {
	Sentence	sent;
	int	i = (int)SvIV(ST(1));
	int	RETVAL;

	if (sv_derived_from(ST(0), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	RETVAL = sentence_disjunct_cost(sent, i);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_sentence_get_word)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::sentence_get_word(sent, wordnum)");
    {
	Sentence	sent;
	int	wordnum = (int)SvIV(ST(1));
	char *	RETVAL;

	if (sv_derived_from(ST(0), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	RETVAL = sentence_get_word(sent, wordnum);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_sentence_length)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::sentence_length(sent)");
    {
	Sentence	sent;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	RETVAL = sentence_length(sent);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_sentence_null_count)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::sentence_null_count(sent)");
    {
	Sentence	sent;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	RETVAL = sentence_null_count(sent);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_sentence_num_linkages_found)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::sentence_num_linkages_found(sent)");
    {
	Sentence	sent;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	RETVAL = sentence_num_linkages_found(sent);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_sentence_num_linkages_post_processed)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::sentence_num_linkages_post_processed(sent)");
    {
	Sentence	sent;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	RETVAL = sentence_num_linkages_post_processed(sent);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_sentence_num_valid_linkages)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Lingua::LinkParser::sentence_num_valid_linkages(sent)");
    {
	Sentence	sent;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	RETVAL = sentence_num_valid_linkages(sent);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_sentence_num_violations)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::sentence_num_violations(sent, i)");
    {
	Sentence	sent;
	int	i = (int)SvIV(ST(1));
	int	RETVAL;

	if (sv_derived_from(ST(0), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	RETVAL = sentence_num_violations(sent, i);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Lingua__LinkParser_sentence_parse)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Lingua::LinkParser::sentence_parse(sent, opts)");
    {
	Sentence	sent;
	Parse_Options	opts;
	int	RETVAL;

	if (sv_derived_from(ST(0), "Sentence")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    sent = (Sentence) tmp;
	}
	else
	    croak("sent is not of type Sentence");

	if (sv_derived_from(ST(1), "Parse_Options")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    opts = (Parse_Options) tmp;
	}
	else
	    croak("opts is not of type Parse_Options");

	RETVAL = sentence_parse(sent, opts);
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Lingua__LinkParser)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Lingua::LinkParser::constant", XS_Lingua__LinkParser_constant, file);
        newXS("Lingua::LinkParser::dictionary_create", XS_Lingua__LinkParser_dictionary_create, file);
        newXS("Lingua::LinkParser::dictionary_delete", XS_Lingua__LinkParser_dictionary_delete, file);
        newXS("Lingua::LinkParser::dictionary_get_max_cost", XS_Lingua__LinkParser_dictionary_get_max_cost, file);
        newXS("Lingua::LinkParser::linkage_and_cost", XS_Lingua__LinkParser_linkage_and_cost, file);
        newXS("Lingua::LinkParser::linkage_compute_union", XS_Lingua__LinkParser_linkage_compute_union, file);
        newXS("Lingua::LinkParser::linkage_create", XS_Lingua__LinkParser_linkage_create, file);
        newXS("Lingua::LinkParser::linkage_delete", XS_Lingua__LinkParser_linkage_delete, file);
        newXS("Lingua::LinkParser::linkage_disjunct_cost", XS_Lingua__LinkParser_linkage_disjunct_cost, file);
        newXS("Lingua::LinkParser::linkage_get_link_domain_names", XS_Lingua__LinkParser_linkage_get_link_domain_names, file);
        newXS("Lingua::LinkParser::linkage_get_link_label", XS_Lingua__LinkParser_linkage_get_link_label, file);
        newXS("Lingua::LinkParser::linkage_get_link_length", XS_Lingua__LinkParser_linkage_get_link_length, file);
        newXS("Lingua::LinkParser::linkage_get_link_llabel", XS_Lingua__LinkParser_linkage_get_link_llabel, file);
        newXS("Lingua::LinkParser::linkage_get_link_lword", XS_Lingua__LinkParser_linkage_get_link_lword, file);
        newXS("Lingua::LinkParser::linkage_get_link_num_domains", XS_Lingua__LinkParser_linkage_get_link_num_domains, file);
        newXS("Lingua::LinkParser::linkage_get_link_rlabel", XS_Lingua__LinkParser_linkage_get_link_rlabel, file);
        newXS("Lingua::LinkParser::linkage_get_link_rword", XS_Lingua__LinkParser_linkage_get_link_rword, file);
        newXS("Lingua::LinkParser::linkage_get_num_links", XS_Lingua__LinkParser_linkage_get_num_links, file);
        newXS("Lingua::LinkParser::linkage_get_num_sublinkages", XS_Lingua__LinkParser_linkage_get_num_sublinkages, file);
        newXS("Lingua::LinkParser::linkage_get_num_words", XS_Lingua__LinkParser_linkage_get_num_words, file);
        newXS("Lingua::LinkParser::linkage_get_sentence", XS_Lingua__LinkParser_linkage_get_sentence, file);
        newXS("Lingua::LinkParser::linkage_get_violation_name", XS_Lingua__LinkParser_linkage_get_violation_name, file);
        newXS("Lingua::LinkParser::linkage_get_word", XS_Lingua__LinkParser_linkage_get_word, file);
        newXS("Lingua::LinkParser::linkage_get_words", XS_Lingua__LinkParser_linkage_get_words, file);
        newXS("Lingua::LinkParser::linkage_has_inconsistent_domains", XS_Lingua__LinkParser_linkage_has_inconsistent_domains, file);
        newXS("Lingua::LinkParser::linkage_is_canonical", XS_Lingua__LinkParser_linkage_is_canonical, file);
        newXS("Lingua::LinkParser::linkage_is_improper", XS_Lingua__LinkParser_linkage_is_improper, file);
        newXS("Lingua::LinkParser::linkage_link_cost", XS_Lingua__LinkParser_linkage_link_cost, file);
        newXS("Lingua::LinkParser::linkage_post_process", XS_Lingua__LinkParser_linkage_post_process, file);
        newXS("Lingua::LinkParser::linkage_print_diagram", XS_Lingua__LinkParser_linkage_print_diagram, file);
        newXS("Lingua::LinkParser::linkage_print_links_and_domains", XS_Lingua__LinkParser_linkage_print_links_and_domains, file);
        newXS("Lingua::LinkParser::linkage_print_postscript", XS_Lingua__LinkParser_linkage_print_postscript, file);
        newXS("Lingua::LinkParser::linkage_set_current_sublinkage", XS_Lingua__LinkParser_linkage_set_current_sublinkage, file);
        newXS("Lingua::LinkParser::linkage_unused_word_cost", XS_Lingua__LinkParser_linkage_unused_word_cost, file);
        newXS("Lingua::LinkParser::parse_options_create", XS_Lingua__LinkParser_parse_options_create, file);
        newXS("Lingua::LinkParser::parse_options_delete", XS_Lingua__LinkParser_parse_options_delete, file);
        newXS("Lingua::LinkParser::parse_options_get_all_short_connectors", XS_Lingua__LinkParser_parse_options_get_all_short_connectors, file);
        newXS("Lingua::LinkParser::parse_options_get_allow_null", XS_Lingua__LinkParser_parse_options_get_allow_null, file);
        newXS("Lingua::LinkParser::parse_options_get_batch_mode", XS_Lingua__LinkParser_parse_options_get_batch_mode, file);
        newXS("Lingua::LinkParser::parse_options_get_disjunct_cost", XS_Lingua__LinkParser_parse_options_get_disjunct_cost, file);
        newXS("Lingua::LinkParser::parse_options_get_display_bad", XS_Lingua__LinkParser_parse_options_get_display_bad, file);
        newXS("Lingua::LinkParser::parse_options_get_display_links", XS_Lingua__LinkParser_parse_options_get_display_links, file);
        newXS("Lingua::LinkParser::parse_options_get_display_on", XS_Lingua__LinkParser_parse_options_get_display_on, file);
        newXS("Lingua::LinkParser::parse_options_get_display_postscript", XS_Lingua__LinkParser_parse_options_get_display_postscript, file);
        newXS("Lingua::LinkParser::parse_options_get_display_union", XS_Lingua__LinkParser_parse_options_get_display_union, file);
        newXS("Lingua::LinkParser::parse_options_get_display_walls", XS_Lingua__LinkParser_parse_options_get_display_walls, file);
        newXS("Lingua::LinkParser::parse_options_get_echo_on", XS_Lingua__LinkParser_parse_options_get_echo_on, file);
        newXS("Lingua::LinkParser::parse_options_get_islands_ok", XS_Lingua__LinkParser_parse_options_get_islands_ok, file);
        newXS("Lingua::LinkParser::parse_options_get_linkage_limit", XS_Lingua__LinkParser_parse_options_get_linkage_limit, file);
        newXS("Lingua::LinkParser::parse_options_get_max_memory", XS_Lingua__LinkParser_parse_options_get_max_memory, file);
        newXS("Lingua::LinkParser::parse_options_get_max_null_count", XS_Lingua__LinkParser_parse_options_get_max_null_count, file);
        newXS("Lingua::LinkParser::parse_options_get_max_parse_time", XS_Lingua__LinkParser_parse_options_get_max_parse_time, file);
        newXS("Lingua::LinkParser::parse_options_get_min_null_count", XS_Lingua__LinkParser_parse_options_get_min_null_count, file);
        newXS("Lingua::LinkParser::parse_options_get_null_block", XS_Lingua__LinkParser_parse_options_get_null_block, file);
        newXS("Lingua::LinkParser::parse_options_get_panic_mode", XS_Lingua__LinkParser_parse_options_get_panic_mode, file);
        newXS("Lingua::LinkParser::parse_options_get_screen_width", XS_Lingua__LinkParser_parse_options_get_screen_width, file);
        newXS("Lingua::LinkParser::parse_options_get_short_length", XS_Lingua__LinkParser_parse_options_get_short_length, file);
        newXS("Lingua::LinkParser::parse_options_get_verbosity", XS_Lingua__LinkParser_parse_options_get_verbosity, file);
        newXS("Lingua::LinkParser::parse_options_memory_exhausted", XS_Lingua__LinkParser_parse_options_memory_exhausted, file);
        newXS("Lingua::LinkParser::parse_options_reset_resources", XS_Lingua__LinkParser_parse_options_reset_resources, file);
        newXS("Lingua::LinkParser::parse_options_resources_exhausted", XS_Lingua__LinkParser_parse_options_resources_exhausted, file);
        newXS("Lingua::LinkParser::parse_options_set_all_short_connectors", XS_Lingua__LinkParser_parse_options_set_all_short_connectors, file);
        newXS("Lingua::LinkParser::parse_options_set_allow_null", XS_Lingua__LinkParser_parse_options_set_allow_null, file);
        newXS("Lingua::LinkParser::parse_options_set_batch_mode", XS_Lingua__LinkParser_parse_options_set_batch_mode, file);
        newXS("Lingua::LinkParser::parse_options_set_cost_model_type", XS_Lingua__LinkParser_parse_options_set_cost_model_type, file);
        newXS("Lingua::LinkParser::parse_options_set_disjunct_cost", XS_Lingua__LinkParser_parse_options_set_disjunct_cost, file);
        newXS("Lingua::LinkParser::parse_options_set_display_bad", XS_Lingua__LinkParser_parse_options_set_display_bad, file);
        newXS("Lingua::LinkParser::parse_options_set_display_links", XS_Lingua__LinkParser_parse_options_set_display_links, file);
        newXS("Lingua::LinkParser::parse_options_set_display_on", XS_Lingua__LinkParser_parse_options_set_display_on, file);
        newXS("Lingua::LinkParser::parse_options_set_display_postscript", XS_Lingua__LinkParser_parse_options_set_display_postscript, file);
        newXS("Lingua::LinkParser::parse_options_set_display_union", XS_Lingua__LinkParser_parse_options_set_display_union, file);
        newXS("Lingua::LinkParser::parse_options_set_display_walls", XS_Lingua__LinkParser_parse_options_set_display_walls, file);
        newXS("Lingua::LinkParser::parse_options_set_echo_on", XS_Lingua__LinkParser_parse_options_set_echo_on, file);
        newXS("Lingua::LinkParser::parse_options_set_islands_ok", XS_Lingua__LinkParser_parse_options_set_islands_ok, file);
        newXS("Lingua::LinkParser::parse_options_set_linkage_limit", XS_Lingua__LinkParser_parse_options_set_linkage_limit, file);
        newXS("Lingua::LinkParser::parse_options_set_max_memory", XS_Lingua__LinkParser_parse_options_set_max_memory, file);
        newXS("Lingua::LinkParser::parse_options_set_max_null_count", XS_Lingua__LinkParser_parse_options_set_max_null_count, file);
        newXS("Lingua::LinkParser::parse_options_set_max_parse_time", XS_Lingua__LinkParser_parse_options_set_max_parse_time, file);
        newXS("Lingua::LinkParser::parse_options_set_min_null_count", XS_Lingua__LinkParser_parse_options_set_min_null_count, file);
        newXS("Lingua::LinkParser::parse_options_set_null_block", XS_Lingua__LinkParser_parse_options_set_null_block, file);
        newXS("Lingua::LinkParser::parse_options_set_panic_mode", XS_Lingua__LinkParser_parse_options_set_panic_mode, file);
        newXS("Lingua::LinkParser::parse_options_set_screen_width", XS_Lingua__LinkParser_parse_options_set_screen_width, file);
        newXS("Lingua::LinkParser::parse_options_set_short_length", XS_Lingua__LinkParser_parse_options_set_short_length, file);
        newXS("Lingua::LinkParser::parse_options_set_verbosity", XS_Lingua__LinkParser_parse_options_set_verbosity, file);
        newXS("Lingua::LinkParser::parse_options_timer_expired", XS_Lingua__LinkParser_parse_options_timer_expired, file);
        newXS("Lingua::LinkParser::post_process_close", XS_Lingua__LinkParser_post_process_close, file);
        newXS("Lingua::LinkParser::post_process_open", XS_Lingua__LinkParser_post_process_open, file);
        newXS("Lingua::LinkParser::sentence_create", XS_Lingua__LinkParser_sentence_create, file);
        newXS("Lingua::LinkParser::sentence_delete", XS_Lingua__LinkParser_sentence_delete, file);
        newXS("Lingua::LinkParser::sentence_disjunct_cost", XS_Lingua__LinkParser_sentence_disjunct_cost, file);
        newXS("Lingua::LinkParser::sentence_get_word", XS_Lingua__LinkParser_sentence_get_word, file);
        newXS("Lingua::LinkParser::sentence_length", XS_Lingua__LinkParser_sentence_length, file);
        newXS("Lingua::LinkParser::sentence_null_count", XS_Lingua__LinkParser_sentence_null_count, file);
        newXS("Lingua::LinkParser::sentence_num_linkages_found", XS_Lingua__LinkParser_sentence_num_linkages_found, file);
        newXS("Lingua::LinkParser::sentence_num_linkages_post_processed", XS_Lingua__LinkParser_sentence_num_linkages_post_processed, file);
        newXS("Lingua::LinkParser::sentence_num_valid_linkages", XS_Lingua__LinkParser_sentence_num_valid_linkages, file);
        newXS("Lingua::LinkParser::sentence_num_violations", XS_Lingua__LinkParser_sentence_num_violations, file);
        newXS("Lingua::LinkParser::sentence_parse", XS_Lingua__LinkParser_sentence_parse, file);
    XSRETURN_YES;
}

